# Generated by Django 3.1.1 on 2020-09-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='categoria',
            field=models.CharField(choices=[], default=12, max_length=50),
            preserve_default=False,
        ),
    ]
