# Generated by Django 3.1.1 on 2020-09-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='categoria',
            field=models.CharField(choices=[('Mundo', 'Mundo'), ('Ambiente', 'Ambiente'), ('Tecnologia', 'Tecnologia'), ('Design', 'Design'), ('Cultura', 'Cultura'), ('Negocio', 'Negocio'), ('Politica', 'Politica')], max_length=50),
        ),
    ]
