# Generated by Django 3.1.1 on 2020-09-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200925_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='categoria',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='categorias',
            field=models.CharField(choices=[('MUN', 'Mundo'), ('AMB', 'Ambiente')], default='MUN', max_length=50),
        ),
    ]
