# Generated by Django 3.1.1 on 2020-09-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200928_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='categorias',
            field=models.CharField(choices=[('MUN', 'Mundo'), ('AMB', 'Ambiente'), ('TEC', 'Tecnologia'), ('DES', 'Design'), ('CUL', 'Cultura'), ('NEG', 'Negocio'), ('POL', 'Politica'), ('OPI', 'Opiniao'), ('CIE', 'Ciencia'), ('SAU', 'Saude'), ('EST', 'Estilo'), ('VIA', 'Viagens')], default='MUN', max_length=50),
        ),
    ]
